routes/web.php
<?php

// use view;


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MapController;
use Illuminate\Support\Facades\Artisan;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('/api')->group(function () {
    Route::get('attractions', 'AttractionController@getAttractions')->name('attractions.get');
    // Route::Resource('/maps', 'API\MapAttractionController')->only(['update', 'destroy']);
});


Route::view('/', 'index')->name('homepage'); // 首頁



Route::resource('/maps', 'MapController'); // 地圖

Route::patch('/maps/{map}/pin', 'MapController@pin');
//eamil 
Route::get('/maps/{map}/itineraries', 'MapController@generateItineraries')->name('maps.itineraries');




Route::resource('attractions', 'AttractionController')->except('create', 'edit'); // 地點
Route::get('/favorites', 'FavoriteController@index')->name('favorites.index');
Route::patch('/attractions/{attraction}/favorite', 'AttractionController@favorite')->name('attractions.favorite'); // 收藏地點

Route::view('/sign-in', 'sign-in')->name('sign-in'); // 登入
Route::view('/sign-up', 'sign-up')->name('sign-up'); // 註冊

// 後台（管理員與一般使用者共用，透過 Gate & PostPolicy 區分權限）
Route::group([
    'prefix' => 'backstage',
    'as' => 'backstage.',
    'middleware' => 'auth'
], function () {
    Route::get('/', 'Backstage\IndexController@index')->name('index'); // 後台首頁
    Route::resource('/users', 'Backstage\UserController')->except('show'); // 後台 - 會員管理
    Route::resource('/maps', 'Backstage\MapController')->except('show'); // 後台 - 地圖管理
    Route::resource('/attractions', 'Backstage\AttractionController')->except(['store', 'update', 'show', 'destroy']); // 後台 - 地點管理
});


// 前端測試用路由
Route::view('/snow', 'Snow.test');
Route::view('/allen', 'Allen.test');



// PDF
Route::group([
    'prefix' => 'pdf',
    'as' => 'pdf',
], function () {
    Route::get('watch', 'MapController@watch');
    Route::get('output', 'MapController@pdfOutput');
});

// 會員模組
Auth::routes();

//faceBook
Route::get('login/facebook', 'Auth\LoginController@facebook')->name('login.facebook');
Route::get('login/facebook/callback', 'Auth\LoginController@facebookCallback');

//github
Route::get('login/github', 'Auth\LoginController@github')->name('login.github');
Route::get('login/github/callback', 'Auth\LoginController@githubCallback');


// Route::get('/home', 'HomeController@index')->name('home');

Route::get('db/reset', function () {
    // dump('Resetting database...');
    // Extend maximum execution time to 3 minutes
    set_time_limit(0);
    Artisan::call('migrate:refresh');
    Artisan::call('db:seed');
    // Back to the default
    set_time_limit(0);
    // Artisan::call('migrate:refresh');
    // Artisan::call('db:seed', ['--class' => DatabaseSeeder::class,]);
    // Artisan::call('migrate:reset', [
    //     '--force' => true
    // ]);
    // Artisan::call('migrate --seed');
    // dd(Artisan::output());
});

resources/views/index.blade.php
@extends('layouts.amigo')

{{-- @section('nav')

@endsection --}}

@section('title')
Buen Camino
@endsection

@section('css')
<style>
  section:not(.index-banner) {
    min-height: 100vh;
  }

  /* 修正子元素無法從父元素繼承 height: 100% 高度的問題 */
  /* section:not(.index-banner)>.container,
  section:not(.index-banner)>.container>.row {
    min-height: inherit;
  } */

  #header {
    height: 100vh;
  }

  .index-banner {
    background-color: var(--mdb-primary);
  }

  .index-banner__description {
    background-color: var(--mdb-primary);
    color: var(--mdb-dark);
  }

  .a-vertical-title {
    display: flex;
    justify-content: center;
    align-items: center;
  }

  @media (min-width: 768px) {
    .a-vertical-title {
      writing-mode: vertical-lr;
      transform: rotate(180deg);
    }
  }
</style>

@endsection


@section('content')
{{-- @include('partials.scroll-indicator') --}}
{{-- <div id="list-example" class="list-group position-fixed">
  <a class="list-group-item list-group-item-action" href="#list-item-1">Item 1</a>
  <a class="list-group-item list-group-item-action" href="#list-item-2">Item2</a>
  <a class="list-group-item list-group-item-action" href="#list-item-3">Item 3</a>
  <a class="list-group-item list-group-item-action" href="#list-item-4">Item 4</a>
</div> --}}
<main>
  <section id="header">
    <div class="h-100 container">
      <div class="h-100 row">
        <div class="h-100 col d-flex flex-column justify-content-center align-items-center">
          <h1 class="mb-5 a-fs-4">突然不知道要去哪裡？</h1>
          <a class="btn btn-secondary btn-lg" href="{{ route('maps.index') }}">探索周遭的地點</a>
        </div>
      </div>
    </div>
  </section>
  <!-- ¿Quién soy yo? / Who am I? -->
  <section id="banner-about-me" class="index-banner py-4">
    <div class="index-banner__description position-sticky bottom-0 a-background" style="background-image: url({{ asset('images/page/index/banner-who-am-III.png') }})">
      <div class="container py-4">
        <div class="row">
          <div class="col-12 col-md-6 text-center d-flex flex-column justify-content-center mb-4 mb-md-0">
            <h1 class="a-fs-3"><b>¿Quién soy yo?</b></h1>
            <h2 class="a-fs-2 text-muted">Who am I?</h2>
          </div>
          <div class="col-12 col-md-6 d-flex flex-column justify-content-center text-center">
            <h3 class="a-fs-0 my-4">
              <b>
                阿米狗是每個人的旅人地圖，<br />
                記錄著那些短暫出現卻又精彩萬分的事物
              </b>
            </h3>
            <p>
              源自於西班牙文中「朋友」的 Amigo 一詞，<br />
              我們就像那位最凱瑞你的朋友！
            </p>
            <p>
              在你的旅途中提供指引，<br />
              將有趣的地點、活動介紹給你就是我們的使命。
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Explore -->
  <section id="features" class="py-5">
    {{-- <section id="features" style="height: 200vh;"> --}}
    <div class="container py-0 py-md-5">
      <div class="row py-0 py-md-5">
        <div class="col d-flex flex-column">
          <!-- Attractions -->
          <div class="row mb-8 mb-md-11">
            <div class="col-12 col-md-2 a-vertical-title mb-3 mb-md-0">
              <h1 class="a-fs-4"><b class="text-primary">A</b><span class="text-dark">ttractions</span></h1>
            </div>
            <div class="col-12 col-md-4 d-flex justify-content-center justify-content-md-start align-items-center mb-5 mb-md-0">
              <div class="w-75 ratio ratio-1x1 rounded-circle border border-3 a-background border-secondary" style="background-image: url({{ asset('images/page/index/attractions.png') }})"></div>
            </div>
            <div class="col-12 col-md-6 d-flex flex-column justify-content-center">
              <h2 class="a-fs-1 mb-4 text-primary text-center text-md-start">「附近有什麼好玩的？」</h2>
              <div class="text-dark mb-2">
                <p>當這句話脫口而出的那一刻，阿米狗便應運而生。</p>
                <p>
                  阿米狗蒐集了世界上各處的有趣地點與活動，<br />
                  也替你留意了那些在匆忙的步伐中隨時可能擦身而過的事物。
                </p>
                <p>
                  想一個人坐在附近的街上靜靜地聽著街頭藝人的低吟淺唱？<br />
                  亦或是在初次拜訪的小鎮上加入熱鬧歡騰的節慶遊行？<br />
                  還是想一個人來趟關於藝術的薰陶之旅？
                </p>
                <p>這些地點，我們都幫你整理好了～</p>
              </div>
              {{-- <div class="text-center text-md-start">
                <a class="btn btn-outline-secondary" data-mdb-ripple-color="secondary" href="{{ route('attractions.index') }}">去看看！</a>
            </div> --}}
          </div>
        </div>
        <!-- Maps -->
        <div class="row flex-row-reverse mb-8 mb-md-11">
          <div class="col-12 col-md-2 a-vertical-title mb-3 mb-md-0" style="transform: rotate(0deg);">
            <h1 class="a-fs-4"><b class="text-primary">M</b><span class="text-dark">ap</span></h1>
          </div>
          <div class="col-12 col-md-4 d-flex justify-content-center justify-content-md-end align-items-center mb-5 mb-md-0">
            <div class="w-75 ratio ratio-1x1 rounded-circle border border-3 a-background border-secondary" style="background-image: url({{ asset('images/page/index/map.png') }})"></div>
          </div>
          <div class="col-12 col-md-6 d-flex flex-column justify-content-center">
            <h2 class="a-fs-1 mb-4 text-primary text-center text-md-start">透過地圖旅行</h2>
            <div class="text-dark mb-2">
              <p>
                遇到喜歡的骨頭就要收藏起來細細品嘗，<br />
                就像看到錢包裡亮晶晶的 50 元硬幣都捨不得花掉！
              </p>
              <p>
                阿米狗替你在地圖上標示出了有趣的地點，<br />
                讓你可以簡單地透過地圖看看附近有什麼有趣的事情。
              </p>
              <p>
                隨手為喜歡的地點按顆星加入收藏，<br />
                晚點就可以集滿周末的行程了！
              </p>
            </div>
            <div class="text-center text-md-end">
              <a class="btn btn-outline-secondary mb-2" data-mdb-ripple-color="secondary" href="{{ route('maps.show', ['map' => 1]) }}">
                看看阿米狗的地圖
                <i class="fas fa-paw ms-1 text-dark" style="transform: rotateZ(-30deg);"></i>
              </a>
              <div class="text-muted">
                <small class="fst-italic">
                  「問我西班牙有哪些有趣的活動？點了不就知道了？」
                </small>
                {{-- <div class="text-end"><small>－－阿米狗，西班牙的地頭貓</small></div> --}}
              </div>
            </div>
          </div>
        </div>
        <!-- Itineraries -->
        <div class="row">
          <div class="col-12 col-md-2 a-vertical-title mb-3 mb-md-0">
            <h1 class="a-fs-4"><b class="text-primary">I</b><span class="text-dark">tineraries</span></h1>
          </div>
          <div class="col-12 col-md-4 d-flex justify-content-center justify-content-md-start align-items-center mb-5 mb-md-0">
            <div class="w-75 ratio ratio-1x1 rounded-circle border border-3 a-background border-secondary" style="background-image: url({{ asset('images/page/index/itineraries.png') }})"></div>
          </div>
          <div class="col-12 col-md-6 d-flex flex-column justify-content-center">
            <h2 class="a-fs-1 mb-4 text-primary text-center text-md-start">獨特的行程表</h2>
            <div class="text-dark mb-2">
              <p>
                收藏起來的地點好想分享給家人朋友們知道？<br />
                阿米狗已經把分享鍵放在收藏頁裡啦！
              </p>
              <p>
                除了可以將喜歡的地點透過收藏按鈕放進屬於自己的收藏頁面以外，<br />
                整理控甚至可以將收藏的地點分門別類放進自己的個人地圖，<br />
                讓你可以將自己的地圖分享給厝邊頭尾～
              </p>
              <p>而且阿米狗也提供了將行程表列印或者是寄送到信箱內的功能！</p>
              <p>
                還猶豫什麼？快揪團出門踏踏吧！
              </p>
            </div>
            <div class="text-center text-md-end">
              <a class="btn btn-outline-secondary mb-2" data-mdb-ripple-color="secondary" href="{{ route('maps.itineraries', ['map' => 1]) }}">
                觀看阿米狗的行程表
                <i class="fas fa-paw ms-1 text-dark" style="transform: rotateZ(-30deg);"></i>
              </a>
              <div class="text-muted">
                <small class="fst-italic">
                  「出去玩沒行程表怎麼行？快按按看這顆魔法按鈕！」
                </small>
                {{-- <div class="text-end"><small>－－阿米狗（現在是貓），喵！</small></div> --}}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </section>
  <section id="banner-about-you" class="index-banner py-4">
    <div class="index-banner__description position-sticky bottom-0 a-background" style="background-image: url({{ asset('images/page/index/banner-who-are-you.png') }})">
      <div class="container py-4">
        <div class="row">
          <div class="col-12 col-md-6 text-center d-flex flex-column justify-content-center mb-4 mb-md-0">
            <h1 class="a-fs-3"><b>¿Quién eres?</b></h1>
            <h2 class="a-fs-2 text-muted">Who are YOU?</h2>
          </div>
          <div class="col-12 col-md-6 d-flex flex-column justify-content-center text-center">
            <h3 class="a-fs-0 my-4">
              <b>
                在旅途中，我們都可能會彼此交會
              </b>
            </h3>
            <p>
              作為旅人，<br />
              在一段旅程中有可能會是一個追尋者，<br />
              也可能會是引導者。
            </p>
            <p>
              在接下來的旅途中，你想當哪一個？
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section id="roles" class="py-5">
    {{-- https://stackoverflow.com/questions/8468066/child-inside-parent-with-min-height-100-not-inheriting-height --}}
    <div class="container py-0 py-md-5">
      <div class="row align-items-center py-0 py-md-5">
        <div class="col-12 col-md-6 text-center mb-8 mb-md-0 d-flex flex-column justify-content-center">
          <h3 class="mb-4 text-primary">
            Traveler<br />
            旅人
          </h3>
          <div class="w-50 ratio ratio-1x1 rounded-circle border border-3 mx-auto mb-5 border-secondary a-background" style="background-image: url({{ asset('images/page/index/role-traveler.png') }})"></div>
          <div class="text-dark">
            <p>旅人，同時也是追尋者。</p>
            <p>
              追尋著那些我們不曾踏足過的境地、<br />
              也追逐著那些不曾映入眼簾的景色。
            </p>
            <p>
              作為旅人，你可以盡情地透過地圖搜尋那些你感興趣的事物，<br />
              並隨時準備好開啟你的旅程！
            </p>
          </div>
        </div>
        <div class="col-12 col-md-6 text-center mb-8 mb-md-0 d-flex flex-column justify-content-center">
          <h3 class="mb-4 text-primary">
            Guider<br />
            嚮導
          </h3>
          <div class="w-50 ratio ratio-1x1 rounded-circle border border-3 mx-auto mb-5 border-secondary a-background" style="background-image: url({{ asset('images/page/index/role-guider.png') }})"></div>
          <div class="text-dark">
            <p>嚮導，同時也是引導者。</p>
            <p>
              引領著旅人打開他們的眼界、<br />
              又或者以藝術感動人心。
            </p>
            <p>
              作為嚮導，你除了像旅人一樣可以使用網站上的所有功能，<br />
              同時也可以在地圖上建立自己的活動。
            </p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col text-center">
          <a class="btn btn-secondary" href="{{ route('sign-up') }}">加入冒險</a>
        </div>
      </div>
    </div>
  </section>
  <section id="banner-the-end" class="index-banner py-4">
    <div class="index-banner__description position-sticky bottom-0 a-background" style="background-image: url({{ asset('images/page/index/buen-camino.png') }}); background-size:">
      <div class="container py-4">
        <div class="row py-0 py-md-4">
          <div class="col-12 text-center d-flex flex-column justify-content-center mb-4">
            <h1 class="a-fs-3"><b>Buen Camino</b></h1>
            <h2 class="a-fs-2 text-muted">一路順風</h2>
          </div>
          <div class="col-12 d-flex flex-column justify-content-center text-center">
            <p>
              <i>在西班牙文中，「Camino」指的是道路；但如今也被代稱為歐洲古老的道路：Camino de Santiago－－意即聖地牙哥朝聖之路。</i>
            </p>
            <p>
              <i>朝聖之路是旅人一路從歐洲前往西班牙聖地牙哥大教堂的路線，途中的旅人會以「Buen Camino」祝福那些同在這條路上風雨同行的彼此。</i>
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>
@endsection

resources/views/sign-in.blade.php
@extends('layouts.amigo')

@section('title')
@parent
旅人簽到
@endsection

@section('nav')
{{-- <div class="position-fixed w-100 text-center h1">
    <a class="logo text-secondary" href="/">Amigo</a>
  </div> --}}
@endsection

@section('css')
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Megrim&display=swap" rel="stylesheet">
<style>
  body {
    background: url('images/sign-in.png') no-repeat center center;
    background-size: cover;
  }

  .container {
    height: 100vh;
  }
</style>
@endsection

@section('content')
<div class="container">
  <div class="row justify-content-center align-items-center h-100">
    <div class="col-10 col-sm-8 col-md-6 col-lg-5">
      <div class="card p-4">
        @if (count($errors) > 0)
        <div class="alert alert-danger" role="alert">
          <ul class="mb-0">
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
          </ul>
        </div>
        <hr class="my-0" />
        @endif
        <div class="card-body text-center">
          <a href="{{ route('homepage') }}">
            <img src="{{ asset('images/logo.svg') }}" alt="Logo" width="60">
          </a>
        </div>
        <div class="card-body px-0">
          <form method="POST" action="{{ route('login') }}">
            @csrf
            {{-- 輸入信箱欄位 --}}
            <div class="form-outline mb-4">
              <input id="login-form__email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autofocus />
              <label class="form-label" for="login-form__email">
                <i class="fas fa-fw fa-envelope me-1"></i>
                Email
              </label>
              {{-- @error('email')
                  <div class="invalid-feedback" role="alert">
                    <strong><small>{{ $message }}</small></strong>
            </div>
            @enderror --}}
        </div>
        {{-- 輸入密碼欄位 --}}
        <div class="form-outline my-4">
          <input id="login-form__password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required />
          <label class="form-label" for="login-form__password">
            <i class="fas fa-fw fa-key me-1"></i>
            Password
          </label>
          {{-- @error('password')
                  <div class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
        </div>
        @enderror --}}
      </div>
      {{-- 記住我 --}}
      <div class="row mb-4">
        <div class="col-6 d-flex align-items-center">
          <div class="form-check">
            <input class="form-check-input" type="checkbox" name="remember" id="remember" {{ old('remember') ? 'checked' : '' }} checked />
            <label class="form-check-label" for="remember">
              <small>給我記住</small>
            </label>
          </div>
        </div>
        <div class="col-6 text-end">
          <div class="row">
            <div class="col-12">
              @if (Route::has('password.request'))
              <a href="{{ route('password.request') }}">
                <small>我忘記密碼了！</small>
              </a>
              @endif
            </div>
            <div class="col-12">
              <a href="{{ route('sign-up') }}">
                <small>先註冊一個帳號</small>
              </a>
            </div>
          </div>
        </div>
      </div>
      <button type="submit" class="btn btn-primary btn-block">登入</button>
      <hr class="a-hr mt-5" data-text="或透過社群網站登入" />
      <div class="d-flex">
        <a class="btn btn-primary w-100 me-2" style="background-color: #3b5998;" href="{{ route('login.facebook') }}" role="button"><i class="fab fa-facebook-f"></i></a>
        <a class="btn btn-primary w-100" style="background-color: #dd4b39;" href="{{ route('login.github') }}" role="button"><i class="fab fa-google"></i></a>
      </div>
      </form>
    </div>
  </div>
</div>
</div>
</div>
@endsection

resources/views/sign-up.blade.php
@extends('layouts.amigo')

@section('title')
@parent
加入冒險
@endsection

@section('nav')

@endsection

@section('css')
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Megrim&display=swap" rel="stylesheet">
<style>
  body {
    /* background-color: #9ad3bc; */
    background: url('images/sign-in.png') no-repeat center center;
    background-size: cover;
    height: 100vh;
  }

  #form_slider {
    /* overflow: hidden; */
    left: 0%;
    transition: left .75s ease-in;
  }

  #form_slider.forward {
    left: -100%
  }

  .role-card {
    height: 50%;
    width: 100%;
    background-color: rgba(255, 255, 255, 0.5);
  }

  /* .role-card:hover {
    background-color: rgba(255, 197, 95, 0.75);
    transition: all .3s linear;
  } */

  @media (min-width: 576px) {
    .role-card__wrapper {
      padding: 0px 20px;
    }
  }

  @media (min-width: 768px) {
    .role-card__wrapper {
      padding: 0px 50px;
    }
  }

  @media (min-width: 992px) {
    .role-card__wrapper {
      padding: 0px 100px;
    }
  }

  @media (min-width: 1200px) {
    .role-card__wrapper {
      padding: 0px 200px;
    }
  }

  @media (min-width: 1400px) {
    .role-card__wrapper {
      padding: 0px 350px;
    }
  }
</style>
@endsection

@section('content')
<div class="d-flex flex-column h-100">
  <form class="flex-grow-1 position-relative overflow-hidden step1" action="{{ route('register') }}" method="POST">
    @csrf
    <div id="form_slider" class="h-100 w-100 position-absolute @if (count($errors) > 0) forward @endif">
      <div class="h-100 w-100 signup-form__choose-role text-center flex-shrink-0 position-absolute">
        {{-- <div class="py-1 text-center text-secondary">
            <p class="mb-1">選擇角色</p>
            <small>透過建立活動可以讓其它使用者透過地圖得知關於你的表演資訊！</small>
          </div> --}}
        <div class="role-card__wrapper d-flex flex-column justift-content-center flex-sm-row py-0 py-sm-5" style="height: 90%;">
          <div class="h-100 role-card d-flex flex-column me-sm-3 py-2 px-sm-3 px-md-5 py-md-3 rounded">
            <div class="form-check">
              <label for="role-Traveler" class="form-check-label text-dark fw-bold">
                <input id="role-Traveler" type="radio" class="form-check-input" value="Traveler" checked name="role">
                旅人 Traveler
              </label>
            </div>
            <small>你是旅人，有著熱愛冒險的靈魂</small>
            <hr />
            <div class="flex-grow-1 a-background" style="background-image: url({{ asset('images/page/sign-up/role-traveler.png') }});">
            </div>
            <hr />
            <small class="text-danger">※無法在網站中建立自己的活動</small>
          </div>

          <div class="h-100 role-card d-flex flex-column ms-sm-3 py-2 px-sm-3 px-md-5 py-md-3 rounded">
            <div class="form-check">
              <label class="form-check-label text-dark fw-bold">
                <input id="role-Artist" type="radio" class="form-check-input" name="role" value="Guider">
                嚮導 Guider
              </label>
            </div>
            <small>比起冒險，你更希望能感動人心</small>
            <hr />
            <div class="flex-grow-1 a-background" style="background-image: url({{ asset('images/page/sign-up/role-guider.png') }});">
            </div>
            <hr />
            <small class="text-success">※可以在網站中建立自己的活動</small>
          </div>

        </div>
        <div class="d-flex flex-column justify-content-center align-items-center" style="height: 10%;">
          <button id="btn_fillForm" class="btn btn-primary d-block" type="button">
            繼續填寫資料
          </button>
        </div>
      </div>
      <div class="h-100 w-100 flex-shrink-0 position-absolute" style="left: 100%;">
        <div class="container" style="height: 90%;">
          <div class="row justify-content-center align-items-center h-100">
            <div class="col-10 col-sm-8 col-md-6 col-lg-5">
              <div class="card">
                <div class="card-body">
                  @if (count($errors) > 0)
                  <div class="alert alert-danger" role="alert">
                    <ul class="mb-0">
                      @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                      @endforeach
                    </ul>
                  </div>
                  <hr class="my-0" />
                  @endif
                </div>
                <div class="card-body text-center">
                  <a href="{{ route('homepage') }}">
                    <img src="{{ asset('images/logo.svg') }}" alt="Logo" width="60">
                  </a>
                </div>
                <div class="card-body p-4">
                  <div class="form__user-info">
                    <div class="form-outline mb-4">
                      <input id="register-form__name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required />
                      <label for="register-form__name" class="form-label">
                        <i class="fas fa-fw fa-user me-1"></i>
                        暱稱
                      </label>
                      {{-- @error('name')
                      <div class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </div>
                    @enderror --}}
                  </div>

                  <!-- 輸入信箱欄位 -->
                  <div class="form-outline mb-4">
                    <input id="register-form__email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required />
                    <label for="register-form__email" class="form-label">
                      <i class="fas fa-fw fa-envelope me-1"></i>
                      Email
                    </label>
                    {{-- @error('email')
                      <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror --}}
                  </div>
                  <div class="row g-2 mb-4">
                    <!-- 輸入密碼欄位 -->
                    <div class="col">
                      <div class="form-outline">
                        <input id="register-form__password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required />
                        <label for="register-form__password" class="form-label">
                          <i class="fas fa-fw fa-key me-1"></i>
                          密碼
                        </label>
                        {{-- @error('password')
                          <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror --}}
                      </div>
                    </div>
                    <!-- 輸入密碼欄位 -->
                    <div class="col mb-4">
                      <div class="form-outline">
                        <input id="register-form__password-confirm" type="password" class="form-control" name="password_confirmation" required />
                        <label for="register-form__password-confirm" class="form-label">
                          確認密碼
                        </label>
                        {{-- @error('password')
                          <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror --}}
                      </div>
                    </div>
                    <div class="col-12 text-end mt-0">
                      <a href="{{ route('sign-in') }}">
                        <small>登入頁面在哪兒？</small>
                      </a>
                    </div>
                  </div>
                  <!-- 按鈕 -->
                  <button type="submit" class="btn btn-primary w-100">註冊</button>
                  <hr class="a-hr mt-5" data-text="或透過社群網站登入" />
                  <div class="d-flex">
                    <a class="btn btn-primary w-100 me-2" style="background-color: #3b5998;" href="{{route('login.facebook')}}" role="button"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-primary w-100" style="background-color: #dd4b39;" href="{{route('login.github')}}" role="button"><i class="fab fa-google"></i></a>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="d-flex flex-column justify-content-center align-items-center" style="height: 10%;">
        <button id="btn_selectRole" class="btn btn-primary d-block" type="button">
          重新選擇角色
        </button>
      </div>
    </div>
</div>
</form>
</div>

@endsection

@section('js')
<script>
  btn_fillForm.addEventListener('click', activeSlider);
  btn_selectRole.addEventListener('click', inactiveSlider);

  function activeSlider() {
    form_slider.classList.add('forward');
  }

  function inactiveSlider() {
    form_slider.classList.remove('forward');
  }
</script>
@endsection