routes/web.php
<?php

// use view;


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MapController;
use Illuminate\Support\Facades\Artisan;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('/api')->group(function () {
    Route::get('attractions', 'AttractionController@getAttractions')->name('attractions.get');
    // Route::Resource('/maps', 'API\MapAttractionController')->only(['update', 'destroy']);
});


Route::view('/', 'index')->name('homepage'); // 首頁



Route::resource('/maps', 'MapController'); // 地圖

Route::patch('/maps/{map}/pin', 'MapController@pin');
//eamil 
Route::get('/maps/{map}/itineraries', 'MapController@generateItineraries')->name('maps.itineraries');




Route::resource('attractions', 'AttractionController')->except('create', 'edit'); // 地點
Route::get('/favorites', 'FavoriteController@index')->name('favorites.index');
Route::patch('/attractions/{attraction}/favorite', 'AttractionController@favorite')->name('attractions.favorite'); // 收藏地點

Route::view('/sign-in', 'sign-in')->name('sign-in'); // 登入
Route::view('/sign-up', 'sign-up')->name('sign-up'); // 註冊

// 後台（管理員與一般使用者共用，透過 Gate & PostPolicy 區分權限）
Route::group([
    'prefix' => 'backstage',
    'as' => 'backstage.',
    'middleware' => 'auth'
], function () {
    Route::get('/', 'Backstage\IndexController@index')->name('index'); // 後台首頁
    Route::resource('/users', 'Backstage\UserController')->except('show'); // 後台 - 會員管理
    Route::resource('/maps', 'Backstage\MapController')->except('show'); // 後台 - 地圖管理
    Route::resource('/attractions', 'Backstage\AttractionController')->except(['store', 'update', 'show', 'destroy']); // 後台 - 地點管理
});


// 前端測試用路由
Route::view('/snow', 'Snow.test');
Route::view('/allen', 'Allen.test');



// PDF
Route::group([
    'prefix' => 'pdf',
    'as' => 'pdf',
], function () {
    Route::get('watch', 'MapController@watch');
    Route::get('output', 'MapController@pdfOutput');
});

// 會員模組
Auth::routes();

//faceBook
Route::get('login/facebook', 'Auth\LoginController@facebook')->name('login.facebook');
Route::get('login/facebook/callback', 'Auth\LoginController@facebookCallback');

//github
Route::get('login/github', 'Auth\LoginController@github')->name('login.github');
Route::get('login/github/callback', 'Auth\LoginController@githubCallback');


// Route::get('/home', 'HomeController@index')->name('home');

Route::get('db/reset', function () {
    // dump('Resetting database...');
    // Extend maximum execution time to 3 minutes
    set_time_limit(0);
    Artisan::call('migrate:refresh');
    Artisan::call('db:seed');
    // Back to the default
    set_time_limit(0);
    // Artisan::call('migrate:refresh');
    // Artisan::call('db:seed', ['--class' => DatabaseSeeder::class,]);
    // Artisan::call('migrate:reset', [
    //     '--force' => true
    // ]);
    // Artisan::call('migrate --seed');
    // dd(Artisan::output());
});

app/Http/Controllers/Backstage/AttractionController.php
<?php

namespace App\Http\Controllers\Backstage;

use App\Tag;
use App\User;
use App\Attraction;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Session;


class AttractionController extends Controller
{
    public function index()
    {
        Session::put('attraction_url',request()->fullUrl());
        $user = Auth::user();
        if (Gate::allows('viewAny', Attraction::class)) {
            if ($user->role == "Admin") {
                $attractions = Attraction::paginate(10);
                return view('backstage.attractions.index', compact('attractions'));
            } else {
                $attractions = Attraction::where('user_id', $user->id)->paginate(10);
                return view('backstage.attractions.index', compact('attractions'));
            }
        }
        return view('backstage.index'); //很抱歉，您的權限不足，發送火箭享尊榮服務
    }



    public function create()
    {
        if (Gate::allows('view-guider', Attraction::class)) {
            $tags = Tag::get();
            return view('backstage.attractions.factory', compact('tags'));
        }
        return view('backstage.index'); //很抱歉，您的權限不足，發送火箭享尊榮服務
    }

    public function edit($id)
    {   
        $tags = Tag::get();
        $attraction = Attraction::with([
            'position',
            'images',
            'tags'
        ])->find($id);
        if (Gate::allows('viewAny', $attraction)) {
            if (auth()->user()->role == "Admin") {
                // dd($attractions);
                return view('backstage.attractions.factory', compact('attraction', 'tags'));
            }
            if (Gate::allows('update', $attraction)) {
                return view('backstage.attractions.factory', compact('attraction', 'tags'));
            }
        }
        return view('backstage.index'); //很抱歉，您的權限不足，發送火箭享尊榮服務
    }
}

app/Http/Controllers/Backstage/IndexController.php
<?php

namespace App\Http\Controllers\backstage;

use App\Attraction;
use App\Http\Controllers\Controller;

class IndexController extends Controller
{
    public function index()
    {
        $putAttraction = Attraction::where('user_id', auth()->user()->id)->count();
        return view('backstage.index', [
            'put' => $putAttraction,
        ]);
    }
}

app/Http/Controllers/Backstage/MapController.php
<?php

namespace App\Http\Controllers\Backstage;

use App\Map;
use App\User;
use Illuminate\Http\Request;

use App\Http\Requests\MapRequest;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class MapController extends Controller
{
    public function index()
    {
        $user = Auth::user();
        if(Gate::allows('viewAny',Map::class)){
            if($user->role == "Admin"){
                $maps = Map::paginate(10);
                return view('backstage.maps.index',compact('maps'));
            }else{
                $maps = Map::where('user_id',$user->id)->paginate(10);
                return view('backstage.maps.index',compact('maps'));
            }
        }
        // return view('backstage.index', compact('maps'));
    }

    public function create()
    {
        if(Gate::allows('create',Map::class)){
        return view('backstage.maps.factory');
        }
        return redirect()->route('backstage.maps.index');
    }

    public function store(MapRequest $request)
    {
        if(Gate::allows('viewAny',map::class)){
            Map::create([
                'user_id' => auth()->user()->id,
                'name' => $request->name
            ]);
        }
        return redirect()->route('backstage.maps.index');   // 發送火箭以加入新的地圖！一起來冒險吧！
    }

    public function edit(Map $map)
    {
        if(Gate::allows('update', $map)){
            return view('backstage.maps.factory', compact('map'));
        }
        return redirect()->route('backstage.maps.index');   // 發送火箭以加入新的地圖！一起來冒險吧！
    }

    public function update(Request $request, Map $map)
    {
        if(Gate::allows('update', $map)){
            $map->update($request->all());
            return redirect()->route('backstage.maps.index');
        }
        return redirect()->route('backstage.maps.index');   // 發送火箭以加入新的地圖！一起來冒險吧！
    }

    public function destroy(Map $map)
    {
        if(Gate::allows('delete', $map)){
            $map->attractions()->detach();
            $map->delete();
            return redirect()->route('backstage.maps.index');
        }
        return redirect()->route('backstage.maps.index');   // 發送火箭以加入新的地圖！一起來冒險吧！
    }
}

app/Http/Controllers/Backstage/UserController.php
<?php

namespace App\Http\Controllers\Backstage;

use App\User;
use App\Http\Requests\UserRequest;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Session;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        Session::put('user_url',request()->fullUrl);
        if (Gate::allows('view-admin')) {
            $users =  User::paginate(10);
            return view('backstage.users.index', compact('users'));
        }
        return view('backstage.index');    //很抱歉，您的權限不足，發送火箭享尊榮服務
    }

    public function create()
    {
        if (Gate::allows('view-admin')) {
            return view('backstage.users.factory');
        }
        return view('backstage.index');    //很抱歉，您的權限不足，發送火箭享尊榮服務
    }

    public function store(UserRequest $request)
    {
        if (Gate::allows('view-admin')) {
            User::create($request->all());
            return redirect()->route('backstage.users.index');
        }
        return view('backstage.index');    //很抱歉，您的權限不足，發送火箭享尊榮服務
    }

    public function edit(User $user)
    {
        if (Gate::allows('view-admin', $user)) {
            return view('backstage.users.factory', compact('user'));
        }
        if(session('user_url')){
            return redirect(session('user_url'));
        }
        return view('backstage.index');    //很抱歉，您的權限不足，發送火箭享尊榮服務
    }

    public function update(UserRequest $request, User $user)
    {
        if (Gate::allows('view-admin', $user)) {
            $user->update($request->all());
            return redirect()->route('backstage.users.index');
        }
        return view('backstage.index');    //很抱歉，您的權限不足，發送火箭享尊榮服務
    }

    public function destroy(User $user)
    {
        if (Gate::allows('view-admin', $user)) {
            $user->attractions()->detach();
            $user->delete();
            return redirect()->route('backstage.users.index');
        }
        return view('backstage.index');    //很抱歉，您的權限不足，發送火箭享尊榮服務
    }
}

resources/views/partials/backstage/footer.blade.php
  <!-- Footer -->
  <footer class="sticky-footer bg-white">
    <div class="container my-auto">
      <div class="copyright text-center my-auto">
        <span>Copyright &copy; Amigo 2021</span>
      </div>
    </div>
  </footer>
  <!-- End of Footer -->

resources/views/partials/backstage/sidebar.blade.php
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-warning sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ route('homepage') }}">
    {{-- <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-map-marked"></i>
    </div> --}}
    <div class="sidebar-brand-text mx-3">
      Amigo
      <sub><i class="fas fa-wrench"></i></sub>
    </div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
    <a class="nav-link" href="{{ route('backstage.index') }}">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>儀表板</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    一般會員
  </div>

  <li class="nav-item">
    <a class="nav-link collapsed" href="#">
      <i class="fas fa-fw fa-id-badge"></i>
      <span>檔案 Profile</span>
    </a>
  </li>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#database-maps">
      <i class="fas fa-fw fa-map"></i>
      <span>地圖 Maps</span>
    </a>
    <div id="database-maps" class="collapse">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">頁面</h6>
        <a class="collapse-item" href="{{route('backstage.maps.index')}}">列表 List</a>
        <a class="collapse-item" href="{{route('backstage.maps.create')}}">新增 Create</a>
      </div>
    </div>
  </li>
  <hr class="sidebar-divider">
  @can('view-guider')
  <!-- Nav Item - Utilities Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#database-attractions">
      <i class="fas fa-fw fa-map-marker-alt"></i>
      <span>地點 Attractions</span>
    </a>
    <div id="database-attractions" class="collapse">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">頁面</h6>
        <a class="collapse-item" href="{{route('backstage.attractions.index')}}">列表 List</a>

        <a class="collapse-item" href="{{route('backstage.attractions.create')}}">新增 Create</a>
      </div>
    </div>
  </li>

  <hr class="sidebar-divider">
  @endcan

  @can('view-admin')
  <div class="sidebar-heading">
    管理員
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#database-users">
      <i class="fas fa-fw fa-users"></i>
      <span>用戶 Users</span>
    </a>
    <div id="database-users" class="collapse">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">頁面</h6>
        <a class="collapse-item" href="{{route('backstage.users.index')}}">列表 List</a>
        <a class="collapse-item" href="{{route('backstage.users.create')}}">新增 Create</a>
      </div>
    </div>
  </li>
  <!-- Divider -->
  <hr class="sidebar-divider">
  @endcan

  {{-- <div class="sidebar-heading">
    快速連結
  </div>

  <li class="nav-item">
    <a class="nav-link collapsed" href="{{ route('homepage') }}">
  <i class="fas fa-fw fa-star"></i>
  <span>Amigo 官方網站</span>
  </a>
  <a class="nav-link collapsed" href="{{ route('sign-up') }}">
    <i class="fas fa-fw fa-user-plus"></i>
    <span>註冊頁面</span>
  </a>
  <a class="nav-link collapsed" href="{{ route('sign-in') }}">
    <i class="fas fa-fw fa-feather-alt"></i>
    <span>登入頁面</span>
  </a>
  <a class="nav-link collapsed" href="{{ route('maps.index') }}">
    <i class="fas fa-fw fa-map"></i>
    <span>地圖頁面</span>
  </a>
  </li> --}}

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>
</ul>
<!-- End of Sidebar -->

resources/views/partials/backstage/topbar.blade.php
 <!-- Topbar -->
 <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

   <!-- Sidebar Toggle (Topbar) -->
   <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
     <i class="fa fa-bars"></i>
   </button>

   {{-- <!-- Topbar Search -->
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
      <div class="input-group">
        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
          aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button class="btn btn-primary" type="button">
            <i class="fas fa-search fa-sm"></i>
          </button>
        </div>
      </div>
    </form> --}}

   <!-- Topbar Navbar -->
   <ul class="navbar-nav ml-auto">

     {{-- <!-- Nav Item - Search Dropdown (Visible Only XS) -->
      <li class="nav-item dropdown no-arrow d-sm-none">
        <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-search fa-fw"></i>
        </a>
        <!-- Dropdown - Messages -->
        <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
          aria-labelledby="searchDropdown">
          <form class="form-inline mr-auto w-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li> --}}

     {{-- <!-- Nav Item - Alerts -->
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-bell fa-fw"></i>
          <!-- Counter - Alerts -->
          <span class="badge badge-danger badge-counter">3+</span>
        </a>
        <!-- Dropdown - Alerts -->
        <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
          aria-labelledby="alertsDropdown">
          <h6 class="dropdown-header">
            Alerts Center
          </h6>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="mr-3">
              <div class="icon-circle bg-primary">
                <i class="fas fa-file-alt text-white"></i>
              </div>
            </div>
            <div>
              <div class="small text-gray-500">December 12, 2019</div>
              <span class="font-weight-bold">A new monthly report is ready to download!</span>
            </div>
          </a>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="mr-3">
              <div class="icon-circle bg-success">
                <i class="fas fa-donate text-white"></i>
              </div>
            </div>
            <div>
              <div class="small text-gray-500">December 7, 2019</div>
              $290.29 has been deposited into your account!
            </div>
          </a>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="mr-3">
              <div class="icon-circle bg-warning">
                <i class="fas fa-exclamation-triangle text-white"></i>
              </div>
            </div>
            <div>
              <div class="small text-gray-500">December 2, 2019</div>
              Spending Alert: We've noticed unusually high spending for your account.
            </div>
          </a>
          <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
        </div>
      </li> --}}

     {{-- <!-- Nav Item - Messages -->
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-envelope fa-fw"></i>
          <!-- Counter - Messages -->
          <span class="badge badge-danger badge-counter">7</span>
        </a>
        <!-- Dropdown - Messages -->
        <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
          aria-labelledby="messagesDropdown">
          <h6 class="dropdown-header">
            Message Center
          </h6>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="dropdown-list-image mr-3">
              <img class="rounded-circle" src="img/undraw_profile_1.svg" alt="...">
              <div class="status-indicator bg-success"></div>
            </div>
            <div class="font-weight-bold">
              <div class="text-truncate">Hi there! I am wondering if you can help me with a
                problem I've been having.</div>
              <div class="small text-gray-500">Emily Fowler · 58m</div>
            </div>
          </a>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="dropdown-list-image mr-3">
              <img class="rounded-circle" src="img/undraw_profile_2.svg" alt="...">
              <div class="status-indicator"></div>
            </div>
            <div>
              <div class="text-truncate">I have the photos that you ordered last month, how
                would you like them sent to you?</div>
              <div class="small text-gray-500">Jae Chun · 1d</div>
            </div>
          </a>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="dropdown-list-image mr-3">
              <img class="rounded-circle" src="img/undraw_profile_3.svg" alt="...">
              <div class="status-indicator bg-warning"></div>
            </div>
            <div>
              <div class="text-truncate">Last month's report looks great, I am very happy with
                the progress so far, keep up the good work!</div>
              <div class="small text-gray-500">Morgan Alvarez · 2d</div>
            </div>
          </a>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="dropdown-list-image mr-3">
              <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="...">
              <div class="status-indicator bg-success"></div>
            </div>
            <div>
              <div class="text-truncate">Am I a good boy? The reason I ask is because someone
                told me that people say this to all dogs, even if they aren't good...</div>
              <div class="small text-gray-500">Chicken the Dog · 2w</div>
            </div>
          </a>
          <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
        </div>
      </li> --}}

     <div class="topbar-divider d-none d-sm-block"></div>

     <!-- Nav Item - User Information -->
     <li class="nav-item dropdown no-arrow">
       <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ Auth::user()->name }}</span>
         <img class="img-profile rounded-circle" src="{{Auth::user()->avatar}}">
       </a>
       <!-- Dropdown - User Information -->
       <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
         <a class="dropdown-item" href="#">
           <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
           個人檔案
         </a>
         {{-- <a class="dropdown-item" href="#">
            <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
            Settings
          </a>
          <a class="dropdown-item" href="#">
            <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
            Activity Log
          </a> --}}
         <div class="dropdown-divider"></div>
         <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
           <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
           登出
         </a>
       </div>
     </li>
   </ul>
 </nav>
 <!-- End of Topbar -->

 <!-- Logout Modal -->
 <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
   <div class="modal-dialog" role="document">
     <div class="modal-content">
       <div class="modal-header">
         <h5 class="modal-title" id="exampleModalLabel">真的要離開嗎 ?</h5>
         <button class="close" type="button" data-dismiss="modal" aria-label="Close">
           <span aria-hidden="true">×</span>
         </button>
       </div>
       <div class="modal-body">建議按取消</div>
       <div class="modal-footer">
         <button class="btn btn-secondary" type="button" data-dismiss="modal">取消</button>
         <a class="btn btn-primary" href="#" onclick="logout_form.submit();">
           登出
         </a>
       </div>
     </div>
   </div>
 </div>

 @include('partials.form.logout-form')

 <!-- Logout Form -->
 {{-- <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
 @csrf
 </form> --}}