routes/web.php
<?php

// use view;


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MapController;
use Illuminate\Support\Facades\Artisan;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('/api')->group(function () {
    Route::get('attractions', 'AttractionController@getAttractions')->name('attractions.get');
    // Route::Resource('/maps', 'API\MapAttractionController')->only(['update', 'destroy']);
});


Route::view('/', 'index')->name('homepage'); // 首頁



Route::resource('/maps', 'MapController'); // 地圖

Route::patch('/maps/{map}/pin', 'MapController@pin');
//eamil 
Route::get('/maps/{map}/itineraries', 'MapController@generateItineraries')->name('maps.itineraries');




Route::resource('attractions', 'AttractionController')->except('create', 'edit'); // 地點
Route::get('/favorites', 'FavoriteController@index')->name('favorites.index');
Route::patch('/attractions/{attraction}/favorite', 'AttractionController@favorite')->name('attractions.favorite'); // 收藏地點

Route::view('/sign-in', 'sign-in')->name('sign-in'); // 登入
Route::view('/sign-up', 'sign-up')->name('sign-up'); // 註冊

// 後台（管理員與一般使用者共用，透過 Gate & PostPolicy 區分權限）
Route::group([
    'prefix' => 'backstage',
    'as' => 'backstage.',
    'middleware' => 'auth'
], function () {
    Route::get('/', 'Backstage\IndexController@index')->name('index'); // 後台首頁
    Route::resource('/users', 'Backstage\UserController')->except('show'); // 後台 - 會員管理
    Route::resource('/maps', 'Backstage\MapController')->except('show'); // 後台 - 地圖管理
    Route::resource('/attractions', 'Backstage\AttractionController')->except(['store', 'update', 'show', 'destroy']); // 後台 - 地點管理
});


// 前端測試用路由
Route::view('/snow', 'Snow.test');
Route::view('/allen', 'Allen.test');



// PDF
Route::group([
    'prefix' => 'pdf',
    'as' => 'pdf',
], function () {
    Route::get('watch', 'MapController@watch');
    Route::get('output', 'MapController@pdfOutput');
});

// 會員模組
Auth::routes();

//faceBook
Route::get('login/facebook', 'Auth\LoginController@facebook')->name('login.facebook');
Route::get('login/facebook/callback', 'Auth\LoginController@facebookCallback');

//github
Route::get('login/github', 'Auth\LoginController@github')->name('login.github');
Route::get('login/github/callback', 'Auth\LoginController@githubCallback');


// Route::get('/home', 'HomeController@index')->name('home');

Route::get('db/reset', function () {
    // dump('Resetting database...');
    // Extend maximum execution time to 3 minutes
    set_time_limit(0);
    Artisan::call('migrate:refresh');
    Artisan::call('db:seed');
    // Back to the default
    set_time_limit(0);
    // Artisan::call('migrate:refresh');
    // Artisan::call('db:seed', ['--class' => DatabaseSeeder::class,]);
    // Artisan::call('migrate:reset', [
    //     '--force' => true
    // ]);
    // Artisan::call('migrate --seed');
    // dd(Artisan::output());
});

app/Http/Controllers/API/AttractionController.php
<?php

namespace App\Http\Controllers\API;


use Illuminate\Http\Request;
use App\Http\Controllers\Controller;



class AttractionController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:api')->only(['favorite']); // 使用者在請求 favorite 時需要驗證身分
    }
    public function index(Request $request)
    {
        // $userFavorites = User::with('attractions')->find('id', auth()->user()->id)->attractions;
        // dd($userFavorites);
        // if ($request->lat && $request->lng) {
        //     $attractions = Attraction::queryNearbyAttractions($request->lat, $request->lng, 3)->with('position', 'images', 'tags')->get();
        // } else {
        //     $attractions = Attraction::with('tags', 'position', 'images')->inRandomOrder()->take(100)->get();
        // }
        // return response(compact('attractions', 'userFavorites'));
    }

    public function favorite($id)
    {
        dd($id, auth()->user());
        // dd(Session::all());
        // dd($id, auth()->user()->name, auth('api')->user());
    }
}

app/Http/Controllers/AttractionController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use App\User;
use App\helpers;
use App\Attraction;
use App\AttractionImage;
use App\AttractionPosition;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\AttractionRequest;

class AttractionController extends Controller
{
    public function store(AttractionRequest $request)
    {
        $user = Auth::user();
        if (Gate::allows('viewAny', Attraction::class)) {
            if ($user->role == "Admin") {
                // 地點轉Px、Py、防止亂傳地址
                $response = helpers::getAddressLatLng($request->address);
                $attraction = Attraction::create([
                    'user_id' => auth()->user()->id,
                    'name' => $request->name,
                    'website' => $request->website,
                    'tel' => $request->tel,
                    'description' => $request->description,
                    'ticket_info' => $request->ticket_info ?? '',
                    'traffic_info' => $request->traffic_info ?? '',
                    'parking_info' => $request->parking_info ?? '',
                ]);
                //position
                $attraction->position()->save(
                    AttractionPosition::make([
                        'country' => $request->country,
                        'region' => $request->region,
                        'town' => $request->town,
                        'address' => $request->address,
                        'lat' =>  $response['lat'],
                        'lng' => $response['lng'],
                    ])
                );
                //tag
                $tag = Tag::find($request->tags);
                $attraction->tags()->attach($tag);
                //img
                if ($request->hasFile('images')) {
                    foreach ($request->file('images') as $key => $image) {
                        $path = $image->store('attractions');
                        $attraction->images()->save(
                            AttractionImage::make([
                                'url' => $path,
                                'image_desc' => $request->image_desc[$key] ?? '',
                            ])
                        );
                    }
                };
                return redirect()->route('backstage.attractions.index');
            }
            if (Gate::allows('create', Attraction::class)) {
                // 地點轉Px、Py
                //這邊要防亂傳地址
                $response = helpers::getAddressLatLng($request->address);

                $attraction = Attraction::create([
                    'user_id' => auth()->user()->id,
                    'name' => $request->name,
                    'website' => $request->website,
                    'tel' => $request->tel,
                    'description' => $request->description,
                    'ticket_info' => $request->ticket_info ?? '',
                    'traffic_info' => $request->traffic_info ?? '',
                    'parking_info' => $request->parking_info ?? '',
                ]);
                //position
                $attraction->position()->save(
                    AttractionPosition::make([
                        'country' => $request->country,
                        'region' => $request->region,
                        'town' => $request->town,
                        'address' => $request->address,
                        'lat' =>  $response['lat'],
                        'lng' => $response['lng'],
                    ])
                );
                //tag
                $tag = Tag::find($request->tags);
                $attraction->tags()->attach($tag);
                //img
                if ($request->hasFile('images')) {
                    foreach ($request->file('images') as $key => $image) {
                        $path = $image->store('attractions');
                        $attraction->images()->save(
                            AttractionImage::make([
                                'url' => $path,
                                'image_desc' => $request->image_desc[$key] ?? '',
                            ])
                        );
                    }
                };
                return redirect()->route('backstage.attractions.index');
            }
        }
        return view('backstage.index');  //很抱歉，您的權限不足，發送火箭享尊榮服務
    }


    public function update(AttractionRequest $request, Attraction $attraction)
    {
        $user = Auth::user();

        if (Gate::allows('viewAny', $attraction)) {
            if ($user->role == "Admin") {

                $attraction->update([
                    'name' => $request->name,
                    'website' => $request->website,
                    'tel' => $request->tel,
                    'description' => $request->description,
                    'ticket_info' => $request->ticket_info ?? '',
                    'traffic_info' => $request->traffic_info ?? '',
                    'parking_info' => $request->parking_info ?? '',
                ]);
                //positcion
                $response = helpers::getAddressLatLng($request->address);
                //之後有空試看看 集合增加的方法
                $attraction->position->update([
                    'country' => $request->country,
                    'region' => $request->region,
                    'town' => $request->town,
                    'address' => $request->address,
                    'lat' =>  $response['lat'],
                    'lng' => $response['lng'],
                ]);
                //tag
                $tag = Tag::find($request->tags);
                $attraction->tags()->SyncWithoutDetaching($tag);
                //img
                if ($request->hasFile('images')) {
                    foreach ($request->file('images') as $key => $image) {
                        $path = $image->store('attractions');
                        AttractionImage::updateOrCreate([
                            'attraction_id' => $attraction->id,
                            'url' => $path,
                        ], [
                            'image_desc' => $request->image_desc[$key] ?? '',
                        ]);
                    };
                };
                if(session('attraction_url')){
                    return redirect(session('attraction_url'));
                }
                return redirect()->route('backstage.attractions.index');
            }

            if (Gate::allows('update', $attraction)) {
                $attraction->update($request->all());
                //positcion
                $response = helpers::getAddressLatLng($request->address);
                //之後有空試看看 集合增加的方法
                $attraction->position->update([
                    'country' => $request->country,
                    'region' => $request->region,
                    'town' => $request->town,
                    'address' => $request->address,
                    'lat' =>  $response['lat'],
                    'lng' => $response['lng'],
                ]);
                //tag
                $tag = Tag::find($request->tags);
                $attraction->tags()->SyncWithoutDetaching($tag);
                //img
                if ($request->hasFile('images')) {
                    foreach ($request->file('images') as $key => $image) {
                        $path = $image->store('attractions');
                        AttractionImage::updateOrCreate([
                            'attraction_id' => $attraction->id,
                            'url' => $path,
                        ], [
                            'image_desc' => $request->image_desc[$key] ?? '',
                        ]);
                    };
                };
                if(session('attraction_url')){
                    return redirect(session('attraction_url'));
                }
                return redirect()->route('backstage.attractions.index');
            }
            return view('backstage.index'); //很抱歉，您的權限不足，發送火箭享尊榮服務
        }
    }



    public function destroy(Attraction $attraction)
    {
        $user = Auth::user();

        if (Gate::allows('viewAny', $attraction)) {
            if ($user->role == "Admin") {
                $attraction->delete();
                $attraction->position->delete();
                $attraction->tags()->detach();
                //開始刪img model跟圖片
                $attraction->images->each(function ($img) {
                    Storage::delete($img->url);
                    $img->delete();
                });
                return redirect()->route('backstage.attractions.index');
            }
            if (Gate::allows('update', $attraction)) {
                $attraction->delete();
                $attraction->position->delete();
                $attraction->tags()->detach();
                //開始刪img model跟圖片
                $attraction->images->each(function ($img) {
                    Storage::delete($img->url);
                    $img->delete();
                });
                return redirect()->route('backstage.attractions.index');
            }
        }

        return view('backstage.index'); //很抱歉，您的權限不足，發送火箭享尊榮服務
        // return redirect()->back()->with('message', 'IT WORKS!');
    }



    public function favorite($id)
    {
        $attraction = Attraction::find($id);
        $isFavorited = Attraction::where('id', $id)->whereHas('users', function ($q) {
            $q->where('user_id', auth()->user()->id);
        })->get()->count();
        if (!$isFavorited) $attraction->users()->attach(auth()->user()->id);
        else $attraction->users()->detach(auth()->user()->id);
        $userFavorites = User::favorites();
      
        return ['userFavorites' => $userFavorites];
    }
    public function getAttractions(Request $request)
    {

app/Http/Controllers/Backstage/AttractionController.php
<?php

namespace App\Http\Controllers\Backstage;

use App\Tag;
use App\User;
use App\Attraction;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Session;


class AttractionController extends Controller
{
    public function index()
    {
        Session::put('attraction_url',request()->fullUrl());
        $user = Auth::user();
        if (Gate::allows('viewAny', Attraction::class)) {
            if ($user->role == "Admin") {
                $attractions = Attraction::paginate(10);
                return view('backstage.attractions.index', compact('attractions'));
            } else {
                $attractions = Attraction::where('user_id', $user->id)->paginate(10);
                return view('backstage.attractions.index', compact('attractions'));
            }
        }
        return view('backstage.index'); //很抱歉，您的權限不足，發送火箭享尊榮服務
    }



    public function create()
    {
        if (Gate::allows('view-guider', Attraction::class)) {
            $tags = Tag::get();
            return view('backstage.attractions.factory', compact('tags'));
        }
        return view('backstage.index'); //很抱歉，您的權限不足，發送火箭享尊榮服務
    }

    public function edit($id)
    {   
        $tags = Tag::get();
        $attraction = Attraction::with([
            'position',
            'images',
            'tags'
        ])->find($id);
        if (Gate::allows('viewAny', $attraction)) {
            if (auth()->user()->role == "Admin") {
                // dd($attractions);
                return view('backstage.attractions.factory', compact('attraction', 'tags'));
            }
            if (Gate::allows('update', $attraction)) {
                return view('backstage.attractions.factory', compact('attraction', 'tags'));
            }
        }
        return view('backstage.index'); //很抱歉，您的權限不足，發送火箭享尊榮服務
    }
}

app/Http/Controllers/Backstage/IndexController.php
<?php

namespace App\Http\Controllers\backstage;

use App\Attraction;
use App\Http\Controllers\Controller;

class IndexController extends Controller
{
    public function index()
    {
        $putAttraction = Attraction::where('user_id', auth()->user()->id)->count();
        return view('backstage.index', [
            'put' => $putAttraction,
        ]);
    }
}

resources/views/backstage/attractions/factory.blade.php
@extends('layouts.backstage')

@section('page-content')
<div class="container-fluid">

  <!-- Page Heading -->
  {{-- <h1 class="h3 mb-2 text-gray-800">地點 | 編輯</h1> --}}

  <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      {{-- <h6 class="m-0 font-weight-bold text-primary">Method -> UPDATE | Action -> {{ route('attractions.update', ['attraction' => $attraction->id]) }}</h6> --}}
      <h6 class="m-0 font-weight-bold text-primary mb-3">地點 |{{ isset($attraction) ? '編輯' : '建立'  }}</h6>
      <div>
        @if (count($errors) > 0)
        <div class="alert alert-danger" role="alert">
          <ul class="mb-0">
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
          </ul>
        </div>
        @endif
      </div>
    </div>

    <div class="card-body">
      <form action="{{ isset($attraction) ? route('attractions.update', ['attraction' => $attraction->id]) : route('attractions.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        @if (isset($attraction))
        @method('PUT')
        @endif
        {{-- --}}
        <p class="text-primary">圖片 Image</p>
        <div id="div_uploaded_images" class="row">
        </div>
        <div class="text-center">
          <a id="btn_upload_image" href="#" class="btn btn-link">
            新增圖片
            <i class="fa fa-plus"></i>
          </a>
        </div>
        <hr />
        {{-- --}}
        <p class="text-primary">標籤 Tags</p>
        <div class="row">
          @for ($i = 1; $i <= 1; $i++) <div class="col">
            <select class="form-control" name="tags[{{ $i }}]">
              <option selected value="">未選擇</option>
              @foreach ($tags as $tag)
              <option value="{{ $tag->id }}">{{ $tag->name }}</option>
              @endforeach
            </select>
        </div>
        @endfor
    </div>
    <hr />
    {{-- --}}
    <p class="text-primary">資訊 Info</p>
    <div class="mb-3">
      <label for="name" class="form-label">名稱 Name *</label>
      <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ $attraction->name ?? old('name') }}" />
    </div>
    <div class="mb-3">
      <label for="description" class="form-label">簡介 Description</label>
      <textarea class="form-control @error('description') is-invalid @enderror" id="description" name="description" rows="3">{{ $attraction->description ?? old('description') }}</textarea>
    </div>
    <div class=" row mb-3">
      <div class="col">
        <label for="website" class="form-label">官方網站 Website</label>
        <input type="text" class="form-control @error('website') is-invalid @enderror" id="website" name="website" value="{{ $attraction->website ?? old('website') }}" />
      </div>
      <div class="col">
        <label for="tel" class="form-label">聯絡電話 Tel</label>
        <input type="text" class="form-control @error('tel') is-invalid @enderror" id="tel" name="tel" value="{{ $attraction->tel ?? old('tel') }}" />
      </div>
    </div>
    <div class="row mb-3">
      <div class="col">
        <label for="ticket_info" class="form-label">售票資訊 Ticket Info</label>
        <input type="text" class="form-control @error('ticket_info') is-invalid @enderror" id="ticket_info" name="ticket_info" value="{{ $attraction->ticket_info ?? old('ticket_info') }}" />
      </div>
      <div class="col">
        <label for="traffic_info" class="form-label">交通資訊 Traffic Info</label>
        <input type="text" class="form-control @error('traffic_info') is-invalid @enderror" id="traffic_info" name="traffic_info" value="{{ $attraction->traffic_info ?? old('traffic_info') }}" />
      </div>
      <div class="col">
        <label for="parking_info" class="form-label">停車資訊 Parking Info</label>
        <input type="text" class="form-control @error('parking_info') is-invalid @enderror" id="parking_info" name="parking_info" value="{{ $attraction->parking_info ?? old('parking_info') }}" />
      </div>
    </div>
    <hr />
    {{-- --}}
    <p class="text-primary">位置 Position</p>
    <div id="city-county-selector" class="row mb-3">
      <div class="col d-none">
        <select name="country" hidden>
          <option value="台灣" selected>台灣</option>
        </select>
      </div>
      <div class="col">
        <label for="select_city" class="form-label">縣市 Region</label>
        <select class="form-control @error('region') is-invalid @enderror" id="select_city" value="{{ $attraction->position->region ?? '' }}"></select>
      </div>
      <div class="col">
        <label for="select_area" class="form-label">區域 Town</label>
        <select class="form-control @error('town') is-invalid @enderror" id="select_area" value="{{ $attraction->position->town ?? '' }}"></select>
      </div>
      <div class="col-12">
        <label for="address" class="form-label">地址 Address</label>
        <input class="form-control @error('address') is-invalid @enderror" id="address" name="address" value="{{ $attraction->position->address ?? old('address') }}" />
      </div>
    </div>
    <hr />
    {{-- --}}
    <button class="btn btn-outline-primary btn-block">{{ isset($attraction) ? '編輯' : '建立'  }}活動</button>
    </form>
  </div>
</div>
</div>
@endsection

@section('js')
<script>
  initTWCitySelector();
</script>
<script>
  let uplodedImageCounter = 0;
  const attraction = @json(isset($attraction) ? $attraction : null);
  if (attraction) {
    attraction.images.forEach(image => {
      createImageBlock(image);
    });
  }

  btn_upload_image.addEventListener('click', () => {
    event.preventDefault();
    createImageBlock();
  });

  function createImageBlock(image = null) {
    const div_col = document.createElement('div');
    div_col.classList.add('col-12');
    div_col.classList.add('col-sm-6');
    div_col.classList.add('col-md-4');
    div_col.classList.add('mb-3');
    div_col.classList.add('text-center');
    div_col.id = `div_uploadedImage_${uplodedImageCounter}`;
    const input_upload_image = document.createElement('input');
    input_upload_image.classList.add('form-control-file');
    input_upload_image.classList.add('mb-1');
    input_upload_image.setAttribute('type', 'file');
    input_upload_image.setAttribute('name', `images[${uplodedImageCounter}]`);
    input_upload_image.dataset.index = uplodedImageCounter;
    const input_image_desc = document.createElement('input');
    input_image_desc.classList.add('form-control');
    input_image_desc.classList.add('form-control-sm');
    input_image_desc.classList.add('mb-1');
    input_image_desc.setAttribute('placeholder', '圖片描述');
    input_image_desc.setAttribute('name', `image_desc[${uplodedImageCounter}]`);
    if (image) input_image_desc.setAttribute('placeholder', image.image_desc);
    const div_preview_image = document.createElement('div');
    div_preview_image.id = `div_preview_image_${uplodedImageCounter}`;
    const btn_delete_image = document.createElement('a');
    btn_delete_image.classList.add('btn_delete_image');
    btn_delete_image.classList.add('text-danger');
    btn_delete_image.dataset.index = uplodedImageCounter;
    btn_delete_image.setAttribute('href', '#');
    btn_delete_image.textContent = image ? '刪除圖片（已上傳）' : '刪除圖片';
    btn_delete_image.style.marginLeft = 'auto';

    div_col.appendChild(div_preview_image);
    div_col.appendChild(input_upload_image);
    div_col.appendChild(input_image_desc);
    div_col.appendChild(btn_delete_image);
    div_uploaded_images.prepend(div_col);
    if (image) createPreviewImageBlock(uplodedImageCounter, image.url);
    uplodedImageCounter++;
  }

  function createPreviewImageBlock(index, src) {
    const div_preview_image = document.getElementById(`div_preview_image_${index}`);
    div_preview_image.innerHTML = '';
    const previewImage = document.createElement('img');
    previewImage.src = src;
    previewImage.classList.add('img-fluid');
    previewImage.classList.add('mb-1');
    div_preview_image.append(previewImage);
  }

  div_uploaded_images.addEventListener('change', (e) => {
    const file = e.target.files[0];
    createPreviewImageBlock(e.target.dataset.index, window.URL.createObjectURL(file));
  });


  div_uploaded_images.addEventListener('click', ({ target: t }) => {
    if (t.className.includes('btn_delete_image')) {
      document.getElementById(`div_uploadedImage_${t.dataset.index}`).remove();
    }
  });
</script>
@endsection

resources/views/backstage/attractions/index.blade.php
@extends('layouts.backstage')

@section('css')

@endsection


@section('page-content')
<div class="container-fluid">

  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800">地點 Attractions</h1>
  <p class="mb-4">
    地點是只有身分別為嚮導（Guider）的使用者才能建立的資源。
  </p>
  <p class="mb-4">
    透過在網站中建立自己的地點，你建立的地點就可以在地圖中被其它使用者搜尋；<br />
    嚮導們可以盡情地在此處上傳自己的活動，透過這種方式讓其它旅人可以加入你的生活！
  </p>

  <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3 d-flex justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">地點列表</h6>
      <h6 class="m-0 font-weight-bold text-primary">資料筆數 {{ $attractions->count() }}</h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered text-center" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>ID</th>
              <th>名稱</th>
              <th>動作</th>
              <th>最後編輯時間</th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <th>ID</th>
              <th>名稱</th>
              <th>動作</th>
              <th>最後編輯時間</th>
            </tr>
          </tfoot>
          <tbody>
            @foreach ($attractions as $a)
            <tr>
              <td>{{ $a->id }}</td>
              <td>{{ $a->name }}</td>
              <td>
                <a href="{{ route('attractions.show', ['attraction' => $a->id]) }}" target="_blank" class="btn btn-info btn-circle btn-sm">
                  <i class="fas fa-external-link-alt"></i>
                </a>
                <a href="{{ route('backstage.attractions.edit', ['attraction' => $a->id]) }}" class="btn btn-warning btn-circle btn-sm">
                  <i class="fas fa-pen"></i>
                </a>

                <a class="btn btn-danger btn-circle btn-sm" href="#" onclick="event.preventDefault();
                  document.getElementById('destroy_form_{{ $a->id }}').submit();">
                  <i class="fas fa-pen"></i>
                </a>

                <form id="destroy_form_{{ $a->id }}" action="{{ route('attractions.destroy', ['attraction' => $a->id]) }}" method="POST" class="d-none">
                  @csrf
                  @method('DELETE')
                </form>
              </td>
              <td>{{ $a->updated_at }}</td>
            </tr>
            @endforeach
          </tbody>
        </table>
        {{$attractions->links()}}
      </div>
    </div>
  </div>

</div>
@endsection


@section('js')
<script>
  // window.onload = () => {
  //   document.querySelectorAll('.delete-btn').forEach(function(btn) {
  //     btn.addEventListener('click', function() {

  //       const id = this.getAttribute('data-id');
  //       if (confirm('是否刪除')) {
  //         document.querySelector(id).submit();
  //       }
  //     });
  //   })
  // }
</script>
@endsection