routes/web.php
<?php

// use view;


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MapController;
use Illuminate\Support\Facades\Artisan;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('/api')->group(function () {
    Route::get('attractions', 'AttractionController@getAttractions')->name('attractions.get');
    // Route::Resource('/maps', 'API\MapAttractionController')->only(['update', 'destroy']);
});


Route::view('/', 'index')->name('homepage'); // 首頁



Route::resource('/maps', 'MapController'); // 地圖

Route::patch('/maps/{map}/pin', 'MapController@pin');
//eamil 
Route::get('/maps/{map}/itineraries', 'MapController@generateItineraries')->name('maps.itineraries');




Route::resource('attractions', 'AttractionController')->except('create', 'edit'); // 地點
Route::get('/favorites', 'FavoriteController@index')->name('favorites.index');
Route::patch('/attractions/{attraction}/favorite', 'AttractionController@favorite')->name('attractions.favorite'); // 收藏地點

Route::view('/sign-in', 'sign-in')->name('sign-in'); // 登入
Route::view('/sign-up', 'sign-up')->name('sign-up'); // 註冊

// 後台（管理員與一般使用者共用，透過 Gate & PostPolicy 區分權限）
Route::group([
    'prefix' => 'backstage',
    'as' => 'backstage.',
    'middleware' => 'auth'
], function () {
    Route::get('/', 'Backstage\IndexController@index')->name('index'); // 後台首頁
    Route::resource('/users', 'Backstage\UserController')->except('show'); // 後台 - 會員管理
    Route::resource('/maps', 'Backstage\MapController')->except('show'); // 後台 - 地圖管理
    Route::resource('/attractions', 'Backstage\AttractionController')->except(['store', 'update', 'show', 'destroy']); // 後台 - 地點管理
});


// 前端測試用路由
Route::view('/snow', 'Snow.test');
Route::view('/allen', 'Allen.test');



// PDF
Route::group([
    'prefix' => 'pdf',
    'as' => 'pdf',
], function () {
    Route::get('watch', 'MapController@watch');
    Route::get('output', 'MapController@pdfOutput');
});

// 會員模組
Auth::routes();

//faceBook
Route::get('login/facebook', 'Auth\LoginController@facebook')->name('login.facebook');
Route::get('login/facebook/callback', 'Auth\LoginController@facebookCallback');

//github
Route::get('login/github', 'Auth\LoginController@github')->name('login.github');
Route::get('login/github/callback', 'Auth\LoginController@githubCallback');


// Route::get('/home', 'HomeController@index')->name('home');

Route::get('db/reset', function () {
    // dump('Resetting database...');
    // Extend maximum execution time to 3 minutes
    set_time_limit(0);
    Artisan::call('migrate:refresh');
    Artisan::call('db:seed');
    // Back to the default
    set_time_limit(0);
    // Artisan::call('migrate:refresh');
    // Artisan::call('db:seed', ['--class' => DatabaseSeeder::class,]);
    // Artisan::call('migrate:reset', [
    //     '--force' => true
    // ]);
    // Artisan::call('migrate --seed');
    // dd(Artisan::output());
});

app/Map.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Map extends Model
{
    use SoftDeletes;
    protected $fillable = [
        'name', 'color', 'user_id',
    ];
    public function user()
    {
        return $this->belongsTo('App\User')->withDefault();
    }
    public function attractions()
    {
        return $this->belongsToMany('App\Attraction', 'map_attraction', 'map_id', 'attraction_id')->withTimestamps();
    }
    static function withRelations($id)
    {
        return Map::with([
            'user',
            'attractions',
            'attractions.images',
            'attractions.position',
            'attractions.time',
            'attractions.tags'
        ])->find($id);
    }
}

app/Http/Controllers/Backstage/AttractionController.php
<?php

namespace App\Http\Controllers\Backstage;

use App\Tag;
use App\User;
use App\Attraction;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Session;


class AttractionController extends Controller
{
    public function index()
    {
        Session::put('attraction_url',request()->fullUrl());
        $user = Auth::user();
        if (Gate::allows('viewAny', Attraction::class)) {
            if ($user->role == "Admin") {
                $attractions = Attraction::paginate(10);
                return view('backstage.attractions.index', compact('attractions'));
            } else {
                $attractions = Attraction::where('user_id', $user->id)->paginate(10);
                return view('backstage.attractions.index', compact('attractions'));
            }
        }
        return view('backstage.index'); //很抱歉，您的權限不足，發送火箭享尊榮服務
    }



    public function create()
    {
        if (Gate::allows('view-guider', Attraction::class)) {
            $tags = Tag::get();
            return view('backstage.attractions.factory', compact('tags'));
        }
        return view('backstage.index'); //很抱歉，您的權限不足，發送火箭享尊榮服務
    }

    public function edit($id)
    {   
        $tags = Tag::get();
        $attraction = Attraction::with([
            'position',
            'images',
            'tags'
        ])->find($id);
        if (Gate::allows('viewAny', $attraction)) {
            if (auth()->user()->role == "Admin") {
                // dd($attractions);
                return view('backstage.attractions.factory', compact('attraction', 'tags'));
            }
            if (Gate::allows('update', $attraction)) {
                return view('backstage.attractions.factory', compact('attraction', 'tags'));
            }
        }
        return view('backstage.index'); //很抱歉，您的權限不足，發送火箭享尊榮服務
    }
}

app/Http/Controllers/Backstage/IndexController.php
<?php

namespace App\Http\Controllers\backstage;

use App\Attraction;
use App\Http\Controllers\Controller;

class IndexController extends Controller
{
    public function index()
    {
        $putAttraction = Attraction::where('user_id', auth()->user()->id)->count();
        return view('backstage.index', [
            'put' => $putAttraction,
        ]);
    }
}

app/Http/Controllers/Backstage/MapController.php
<?php

namespace App\Http\Controllers\Backstage;

use App\Map;
use App\User;
use Illuminate\Http\Request;

use App\Http\Requests\MapRequest;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class MapController extends Controller
{
    public function index()
    {
        $user = Auth::user();
        if(Gate::allows('viewAny',Map::class)){
            if($user->role == "Admin"){
                $maps = Map::paginate(10);
                return view('backstage.maps.index',compact('maps'));
            }else{
                $maps = Map::where('user_id',$user->id)->paginate(10);
                return view('backstage.maps.index',compact('maps'));
            }
        }
        // return view('backstage.index', compact('maps'));
    }

    public function create()
    {
        if(Gate::allows('create',Map::class)){
        return view('backstage.maps.factory');
        }
        return redirect()->route('backstage.maps.index');
    }

    public function store(MapRequest $request)
    {
        if(Gate::allows('viewAny',map::class)){
            Map::create([
                'user_id' => auth()->user()->id,
                'name' => $request->name
            ]);
        }
        return redirect()->route('backstage.maps.index');   // 發送火箭以加入新的地圖！一起來冒險吧！
    }

    public function edit(Map $map)
    {
        if(Gate::allows('update', $map)){
            return view('backstage.maps.factory', compact('map'));
        }
        return redirect()->route('backstage.maps.index');   // 發送火箭以加入新的地圖！一起來冒險吧！
    }

    public function update(Request $request, Map $map)
    {
        if(Gate::allows('update', $map)){
            $map->update($request->all());
            return redirect()->route('backstage.maps.index');
        }
        return redirect()->route('backstage.maps.index');   // 發送火箭以加入新的地圖！一起來冒險吧！
    }

    public function destroy(Map $map)
    {
        if(Gate::allows('delete', $map)){
            $map->attractions()->detach();
            $map->delete();
            return redirect()->route('backstage.maps.index');
        }
        return redirect()->route('backstage.maps.index');   // 發送火箭以加入新的地圖！一起來冒險吧！
    }
}

app/Http/Controllers/Backstage/UserController.php
<?php

namespace App\Http\Controllers\Backstage;

use App\User;
use App\Http\Requests\UserRequest;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Session;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        Session::put('user_url',request()->fullUrl);
        if (Gate::allows('view-admin')) {
            $users =  User::paginate(10);
            return view('backstage.users.index', compact('users'));
        }
        return view('backstage.index');    //很抱歉，您的權限不足，發送火箭享尊榮服務
    }

    public function create()
    {
        if (Gate::allows('view-admin')) {
            return view('backstage.users.factory');
        }
        return view('backstage.index');    //很抱歉，您的權限不足，發送火箭享尊榮服務
    }

    public function store(UserRequest $request)
    {
        if (Gate::allows('view-admin')) {
            User::create($request->all());
            return redirect()->route('backstage.users.index');
        }
        return view('backstage.index');    //很抱歉，您的權限不足，發送火箭享尊榮服務
    }

    public function edit(User $user)
    {
        if (Gate::allows('view-admin', $user)) {
            return view('backstage.users.factory', compact('user'));
        }
        if(session('user_url')){
            return redirect(session('user_url'));
        }
        return view('backstage.index');    //很抱歉，您的權限不足，發送火箭享尊榮服務
    }

    public function update(UserRequest $request, User $user)
    {
        if (Gate::allows('view-admin', $user)) {
            $user->update($request->all());
            return redirect()->route('backstage.users.index');
        }
        return view('backstage.index');    //很抱歉，您的權限不足，發送火箭享尊榮服務
    }

    public function destroy(User $user)
    {
        if (Gate::allows('view-admin', $user)) {
            $user->attractions()->detach();
            $user->delete();
            return redirect()->route('backstage.users.index');
        }
        return view('backstage.index');    //很抱歉，您的權限不足，發送火箭享尊榮服務
    }
}

app/Http/Controllers/MapController.php
<?php

namespace App\Http\Controllers;

use App\Map;
use App\User;
use App\helpers;
use App\Attraction;
use App\Mail\Itineraries;
use Illuminate\Http\Request;
use Illuminate\Mail\Markdown;
use App\Http\Requests\MapRequest;
use Barryvdh\DomPDF\Facade as PDF;
use Illuminate\Support\Facades\Mail;

class MapController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except('index', 'show', 'generateItineraries');
    }

    public function index(Request $request)
    {
        $user = auth()->user() ?? null;
        $map = null;
        $mapAttractions = [];
        $userFavorites = User::favorites();
        $userPersonalMaps = User::personalMaps();
        $searchResult = $this->searchAttractions($request);
        $attractions = $searchResult['attractions'];
        $addressLatLng = $searchResult['addressLatLng'];
        return view('maps.index', compact('attractions', 'addressLatLng', 'userFavorites', 'map', 'mapAttractions', 'user', 'userPersonalMaps'));
    }

    public function create()
    {
        return view('maps.factory');
    }

    public function store(Request $request)
    {
        $map = Map::create([
            'user_id' => auth()->user()->id,
            'name' => $request->name ?? auth()->user()->name . '的旅人地圖',
        ]);
        return redirect()->route('maps.show', ['map' => $map->id]);
    }

    public function show(Request $request, $id)
    {
        $userPersonalMaps = User::personalMaps();
        $searchResult = $this->searchAttractions($request);
        $attractions = $searchResult['attractions'];
        $addressLatLng = $searchResult['addressLatLng'];
        // $attractions =  Attraction::with('tags', 'position', 'images', 'time')->take(10)->get();
        // $addressLatLng = null;
        $user = auth()->user() ?? null;
        $map = Map::withRelations($id);
        // $mapAttractions = $map->attractions->pluck('id');
        $mapAttractions = $map->attractions;
        $userFavorites = User::favorites();
        return view('maps.index', [
            'map' => $map,
            'mapAttractions' => $mapAttractions,
            'userFavorites' => $userFavorites,
            'addressLatLng' => $addressLatLng,
            'attractions' => $attractions,
            'user' => $user,
            'userPersonalMaps' => $userPersonalMaps
        ]);
    }

    public function edit($id)
    {
        $action = 'Edit';
        return view('maps.factory', compact('action'));
    }

    public function update(MapRequest $request, Map $map)
    {
        if ($request->name) {
            $map->update([
                'name' => $request->name,
            ]);
        };
        return redirect()->route('maps.show', ['map' => $map->id]);
    }

    public function destroy(Map $map)
    {
        $map->attractions()->detach();
        $map->delete();
    }
    public function pin(Request $request, $id)
    {
        $attraction = Attraction::findOrFail($request->attractionId);
        $isPinned = Map::where('id', $id)->whereHas('attractions', function ($query) use ($attraction) {
            $query->where('attraction_id', $attraction->id);
        })->get()->count();

        $map = Map::with([
            'attractions',
        ])->find($id);
        if (!$isPinned) $map->attractions()->attach($attraction);
        else $map->attractions()->detach($attraction);
        // $mapAttractions = Map::with('attractions')->find($id)->attractions->pluck('id'); // 如果使用 $map-> 會取得更新前的舊陣列
        $mapAttractions = Map::withRelations($id)->attractions;
        return compact('mapAttractions');
    }
    public function generateItineraries($mapId)
    {
        if ($mapId === 1) $this->middleware('auth')->except('generateItineraries');

        if (auth()->check()) $user = auth()->user();
        else $user = User::find(1);
        $map = Map::with([
            'attractions',
            'attractions.position'
        ])->whereHas('attractions', function ($query) use ($mapId) {
            $query->where('map_id', $mapId);
        })->get()->first();

        set_time_limit(0);
        Mail::send(new Itineraries($map, $user));
        // set_time_limit(0);
        $markdown = new Markdown(view(), config('mail.markdown'));
        return $markdown->render('emails.itineraries', compact('map', 'user'));
        // Mail::send(new amigo_map($all));
        // return redirect()->route('sign-in');
    }

    // public function watch()
    // {
    //     // ->setOptions(['defaultFont' => 'sans-serif'])
    //     $pdf = PDF::loadView('emails.PDF');
    //     return $pdf->stream();
    //     // return $pdf->download('amigo.pdf');
    // }
    // public function pdfOutput()
    // {
    //     $userFavorites = User::with([
    //         'attractions',
    //         'attractions.position',
    //     ])->findOrFail(auth()->user()->id);
    //     Mail::send(new Itineraries($userFavorites));
    // }
    private function searchAttractions($request)
    {
        $addressLatLng = null;
        $query = Attraction::query()->with('tags', 'position', 'images', 'time');
        if ($request->tag) $query->queryTags($request->tag);
        switch ($request->searchBy) {
            case 'area':
                $addressLatLng = helpers::getAddressLatLng($request->q);
                $query->queryNearbyAttractions($addressLatLng['lat'], $addressLatLng['lng'], $request->range);
                $attractions = $query->get();
                break;
            case 'address':
                if ($request->region) $query->queryRegion($request->region);
                if ($request->town) $query->queryTown($request->town);
                $attractions = $query->get();
                break;
            default:
                $addressLatLng = null;
                $attractions = [];
                break;
        }
        return compact('attractions', 'addressLatLng');
    }
}

resources/views/backstage/maps/factory.blade.php
@extends('layouts.backstage')

@section('page-content')
<div class="container-fluid">

  <!-- Page Heading -->
  {{-- <h1 class="h3 mb-2 text-gray-800">地點 | 編輯</h1> --}}

  <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      {{-- <h6 class="m-0 font-weight-bold text-primary">Method -> UPDATE | Action -> {{ route('attractions.update', ['attraction' => $attraction->id]) }}</h6> --}}
      <h6 class="m-0 font-weight-bold text-primary mb-3">個人地點 | {{isset($map) ? '編輯' :'新增'}}</h6>
      <div>
        @if (count($errors) > 0)
        <div class="alert alert-danger" role="alert">
          <ul class="mb-0">
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
          </ul>
        </div>
        @endif
      </div>
    </div>

    <div class="card-body">
      <form action="{{ isset($map) ? route('backstage.maps.update', ['map' => $map->id]) : route('backstage.maps.store') }}" method="POST">
        @csrf
        @if (isset($map))
        @method('PUT')
        @endif
        {{-- --}}
        <p class="text-primary">資訊 Info</p>
        <div class="mb-3">
          <label for="name" class="form-label">名稱 Name</label>
          <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ $map->name ?? old('name') }}" />
        </div>
        {{-- --}}
        <button class="btn btn-outline-primary btn-block">{{isset($map) ? '編輯' :'建立'}}個人地圖</button>
      </form>
    </div>
  </div>
</div>
@endsection

resources/views/backstage/maps/index.blade.php
@extends('layouts.backstage')

@section('css')
@endsection

@section('page-content')
<div class="container-fluid">

  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800">地圖 Maps</h1>
  <p class="mb-4">
    地圖是網站所有使用者都能建立的資源。
  </p>
  <p class="mb-4">
    透過在網站中建立地圖，你可以地點（Attractions）分門別類地放進你建立的地圖中；<br />
    並且也可以將地圖的網址分享給其它旅人，讓它們看看你規劃的行程有多棒！
  </p>
  <p class="mb-4">
    <a href="#" class="btn btn-warning btn-circle btn-sm">
      <i class="fas fa-pen"></i>
    </a>
    <span class="align-middle">可變更地圖名稱</span>
  </p>
  <p class="mb-4">
    <a href="#" target="_blank" class="btn btn-info btn-circle btn-sm">
      <i class="fas fa-external-link-alt"></i>
    </a>
    <span class="align-middle">可在地圖介面中編輯地圖，並把地點（Attractions）加入地圖中</span>
  </p>

  <!-- DataTales Example -->
  <div class="card shadow mb-4">
    {{-- 這邊我加d-flex justify-content-between --}}
    <div class="card-header py-3 d-flex justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">地圖列表</h6>
      <h6 class="m-0 font-weight-bold text-primary">資料筆數 {{ $maps->count() }}</h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered text-center" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              @can('view-admin')
              <th>ID</th>
              <th>建立者</th>
              @endcan
              <th>名稱</th>
              <th>動作</th>
              <th>最後編輯時間</th>
            </tr>
          </thead>
          {{-- <tfoot>
            <tr>
              <th>ID</th>
              <th>user_id</th>
              <th>名稱</th>
              <th>動作</th>
              <th>最後編輯時間</th>
            </tr>
          </tfoot> --}}
          <tbody>
            @foreach ($maps as $m)
            <tr>
              @can('view-admin')
              <td>{{ $m->id }}</td>
              <td>{{ $m->user_id }}</td>
              @endcan
              <td>{{ $m->name }}</td>
              <td>
                <a href="{{ route('maps.show', ['map' => $m->id]) }}" target="_blank" class="btn btn-info btn-circle btn-sm">
                  <i class="fas fa-external-link-alt"></i>
                </a>
                <a href="{{ route('backstage.maps.edit', ['map' => $m->id]) }}" class="btn btn-warning btn-circle btn-sm">
                  <i class="fas fa-pen"></i>
                </a>
                <a class="btn btn-danger btn-circle btn-sm" onclick="event.preventDefault();
                document.getElementById('delete_form_{{ $m->id }}').submit();">
                  <i class="fas fa-trash"></i>
                </a>
                <form id="delete_form_{{ $m->id }}" action="{{ route('backstage.maps.destroy', ['map' => $m->id]) }}" method="POST" class="d-none">
                  @csrf
                  @method('DELETE')
                </form>
              </td>
              <td>{{ $m->updated_at }}</td>
            </tr>
            @endforeach
          </tbody>
        </table>
        {{$maps->links()}}
      </div>
    </div>
  </div>

</div>
@endsection

@section('js')
@endsection